const router = require("express").Router();
const Util = require("../Controller/Utilisateur.Controller");
const Chek = require("../middleware/auth.middleware");
router.post("/CreeCompte",Util.CreeCompte);
router.post("/Connection", Util.Connection);
router.get("/Deconnection", Chek.ChekUser, Util.Deconnection);
router.get("/RecupCl",Chek.ChekUser, Util.RecupCl);
router.get("/GetAllUsers", Util.getAllUsers);
router.get("/Compte", Util.getUser);
router.post("/User", Util.getUser2);
router.post("/Modifier", Util.Modifier);
router.delete("/SupprimerUser", Util.SupprimeUser);
router.post("/Encherir", Util.Encherir);
router.post("/Cloturer", Util.Cloturer);
router.post("/AjoutProduit",Util.AjoutProduit);
router.post("/RechercheProduit",Util.Recherche);
router.delete("/SupprimerProduit", Util.SupprimeProduit);
router.get("/GetAllProducts", Util.getAllProducts);
router.get("/GetAllEncheres", Util.getAllEncheres);
router.post("/GetProduct", Util.getProduct);
module.exports = router;
